version: "3.9"
services:
  episode-switcher:
    build: .
    image: episode-watcher:1.0.0-SNAPSHOT
    hostname: app
  keycloak-episode-switcher-db:
    image: "postgres:13-alpine"
    hostname: postgresql
    environment:
      - POSTGRES_USER=bn_keycloak
      - POSTGRES_DB=bitnami_keycloak
      - POSTGRES_PASSWORD=${KEYCLOAK_POSTGRES_PASSWORD}
    volumes:
      - keycloak_pg_data:/var/lib/postgresql/data
  keycloak-episode-switcher:
    image: "bitnami/keycloak:18"
    hostname: keycloak
    depends_on:
      - keycloak-episode-switcher-db
    environment:
      - KEYCLOAK_DATABASE_PASSWORD=${KEYCLOAK_POSTGRES_PASSWORD}
  nginx-episode-switcher:
    image: "nginx:1.23-alpine"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

volumes:
  keycloak_pg_data:
    driver: local